### ISSUE TITLE
Print docstring for standard namespaces 

### ISSUE THREAD

**Issue by tomasz-biernacki** [ScalaConsultants/replumb#47] opened 2015-12-01 11:40 UTC
`doc` doesn't work for standard namespaces (eg. `clojure.set`):
Moreover, there are different output in the other repls:

**replumb**:
```
cljs.user=> (doc clojure.set)
-------------------------
clojure/set
  nil

cljs.user=> (require 'clojure.set)
nil
cljs.user=> (doc clojure.set)
-------------------------
clojure/set
  nil
```

**planck**:
```
cljs.user=> (doc clojure.set)
-------------------------
clojure/set
  nil
nil
cljs.user=> (require 'clojure.set)
nil
cljs.user=> (doc clojure.set)
-------------------------
clojure.set
  Set operations such as union/intersection.
nil
```

**lein repl**:
```
user=> (doc clojure.set)
-------------------------
clojure.set
  nil
nil
user=> (require 'clojure.set)
nil
user=> (doc clojure.set)
-------------------------
clojure.set
  nil
nil
```

**cljs repl**
```
cljs.user=> (doc clojure.set)
-------------------------
clojure.set
  Set operations such as union/intersection.

nil
```

**Comment by mfikes** [comment] 2015-12-03 01:48
@tomasz-biernacki: I can't reproduce your *cljs repl* experience. (I tried with the browser REPL from Quick Start and Node (`script/noderepljs` in the ClojureScript code tree.) Do you perhaps have a `:repl-requires` set to automatically require `clojure.set`?

Planck's output looks correct, IMHO, but this is only fixed in master https://github.com/mfikes/planck/issues/151

**Comment by tomasz-biernacki** [comment] 2015-12-08 01:32
@mfikes Hi, maybe the *cljs repl* name it not appropriate, anyway it's the figwheel repl. 
When you start the project with `lein fig-dev*` you can check in the repl that we don't need to require `clojure.set` but I haven't investigated why.

**Comment by arichiardi** [comment] 2015-12-08 05:58
I tried also for `clojure.string` and I report here my observations:

*lein repl*:
```
user=> (require 'clojure.string)
nil
user=> (doc clojure.string/trim)
-------------------------
clojure.string/trim
([s])
  Removes whitespace from both ends of string.
nil
```

*lein node-repl* (I guess lein fig-dev* is the same)
```
cljs.user=> (require 'clojure.string)
nil
cljs.user=> (doc clojure.string/trim)
-------------------------
clojure.string/trim
  nil
```

**Comment by arichiardi** [comment] 2015-12-08 06:03
@tomasz-biernacki there is a difference in the [else](https://github.com/mfikes/planck/commit/173005b4c5bf8b04aa6b4b42f8ff3ad5c3025ff1#diff-13fa1297261809d0414872aca47177beR664) clause if I am not wrong...or maybe `get-var` reflects that?

**Comment by arichiardi** [comment] 2015-12-08 06:08
I would also add the test case in `repl_test.cljs`:
```
(let [res (do (repl/read-eval-call {} validated-echo-cb "(require 'clojure.set)")
                    (repl/read-eval-call {} validated-echo-cb "(doc clojure.set)")
     )
```

**Comment by arichiardi** [comment] 2015-12-08 17:16
It might also be that `planck` has bundled all the dependencies and therefore `*load-fn*` is actually returning the source (with docs). I have not tested this statement, maybe the two are not related, but I will soon.

**Comment by arichiardi** [comment] 2015-12-08 18:18
My above statement was right, by just adding `out` as part of the new option `:src-paths` solves the problem -> https://github.com/ScalaConsultants/replumb/commit/de063d5c61b10db1298f4eb6a21793ae173407c0

```
Starting Node.js sample repl:
 [:target :nodejs] 
 [:src-paths [dev-resources/private/node/compiled/out dev-resources/private/test/src/cljs dev-resources/private/test/src/clj]] 
 [:verbose false]
cljs.user=> (require 'clojure.set)
nil
cljs.user=> (doc clojure.set)
-------------------------
clojure.set
  Set operations such as union/intersection.
```

**Comment by arichiardi** [comment] 2015-12-09 23:00
I am leaving this open in order to remember to add this tests for it.

**Comment by tomasz-biernacki** [comment] 2015-12-10 16:00
@arichiardi yes, in the node repl it works but still it doesn't work in the browser version (`lein fig-dev*`)
Is this related to some other issue?

**Comment by arichiardi** [comment] 2015-12-10 16:03
Yes, for the browser you have to check the `add-browser-io` branch. It works fine.  I will need to write a wiki page on require only. A lot of things to share.

**Comment by arichiardi** [comment] 2015-12-10 16:04
I will add the test in that branch

**Closed** 2015-12-11 04:01 UTC
Labels: bug, tests wanted
